---
- name: Install XCode
  command: xcode-select --install

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest upgrade_all=yes update_homebrew=yes
  with_items:
    - ack
    - curl
    - git
    - nmap
    - node
    - python
    - python3
    - readline
    - rename
    - ssh-copy-id
    - vim
    - watch
    - wget
    - zsh
    - zsh-completions
    - httpie
    - tree
    - openssl
    - coreutils
    - findutils
    - htop
    - maven
    - gpg
    - nvm
    - byobu

- name: Install Sask
  homebrew: name=cask state=latest
- name: Install apps with Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - atom
    - iterm2
    - macpass
    - vlc
    - vagrant
    - vagrant-manager
    - github-desktop
    - virtualbox
    - spotify
    - google-chrome
    - slack

## TO-DO
## Here install this: https://github.com/chriskempson/tomorrow-theme/tree/master/iTerm2

- name: Cleanup Brew packages
  command: brew cleanup
