---
- name: Install/Update XCode
  script: "{{ playbook_dir }}/roles/osx/files/xcode.sh"

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest upgrade_all=yes update_homebrew=yes
  with_items:
    - ack
    - curl
    - git
    - nmap
    - node
    - python3
    - autoenv
    - readline
    - rename
    - ssh-copy-id
    - vim
    - watch
    - wget
    - zsh
    - zsh-completions
    - httpie
    - tree
    - openssl
    - coreutils
    - findutils
    - htop
    - gpg
    - nvm
    - byobu
    - vhs
    - glow
    - golang
    - lnav
    - ncdu
#    - warrensbox/tap/tfswitch
    - awscli
    - mitmproxy
#    - bindfs
    - kubectx
    - jq
    - python-yq
#    - youtube-dl
    - ffmpeg
    - espeak
    - sox
    - dbeaver-community
    - microsoft-teams
    - slack
    - tunnelblick
#    - tldr
    - google-cloud-sdk
    - kind
    - helm
    - kubectl
    - k9s
    - fluxcd/tap/flux
    - dive
    - danielfoehrkn/switch/switch
    - pyenv
    - pyenv-virtualenv
    - zplug
  ignore_errors: yes

# Workaround: This applies to vagrant box I am using to verify
- file: path=/usr/local/bin/brew-cask state=absent force=yes

- name: Install fonts Cask repository
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install tap cask versions
  homebrew_tap:
    name: homebrew/cask-versions

- name: Install apps with Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - visual-studio-code
    - iterm2
    - macpass
#    - vagrant
#    - virtualbox
    - spotify
    - google-chrome
    - firefox
    - oracle-jdk
    - insomnia
    - keepassxc
    - spectacle
    - font-inconsolata
    - brave-browser
    - owasp-zap
    - font-hack-nerd-font
    - jetbrains-toolbox
    - docker
    # - android-studio
    # - cocoapods
    # - flutter  

# This requires Java that comes by Cask
# - name: Install Maven
#   homebrew: name=maven state=latest

- name: Cleanup Brew packages
  command: brew cleanup
