---
- name: Install/Update XCode
  script: "{{ playbook_dir }}/roles/osx/files/xcode.sh"

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest upgrade_all=yes update_homebrew=yes
  with_items:
    - ack
    - curl
    - git
    - nmap
    - node
    - python
    - python3
    - autoenv
    - readline
    - rename
    - ssh-copy-id
    - vim
    - watch
    - wget
    - zsh
    - zsh-completions
    - httpie
    - tree
    - openssl
    - coreutils
    - findutils
    - htop
    - gpg
    - nvm
    - byobu
    - asciinema
    - asciinema2gif
    - golang
    - lnav
    - ncdu

# Workaround: This applies to vagrant box I am using to verify
- file: path=/usr/local/bin/brew-cask state=absent force=yes

- name: Install fonts Cask repository
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install apps with Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
#    - atom
    - visual-studio-code
    - iterm2
    - macpass
    - vagrant
    - vagrant-manager
    - virtualbox
    - spotify
    - google-chrome
    - slack
    - java8 # Will fail without brew cask tap cask/versions
    - java
    - insomnia
    - bindfs
    - mitmproxy
    - dash
    - keepassxc
    - spectacle
    - font-inconsolata
#    - gitkraken 
#    - rambox

# This requires Java that comes by Cask
- name: Install Maven
  homebrew: name=maven state=latest

- name: Cleanup Brew packages
  command: brew cleanup

- name: Install iterm2
  mac_pkg: pkg_type=app url=https://iterm2.com/downloads/stable/iTerm2-2_1_4.zip archive_type=zip archive_path=iTerm.app
  become: yes
  become_method: sudo