---
- name: Install XCode
  command: xcode-select --install

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - curl
    - git
    - nmap
    - node
    - python
    - python3
    - readline
    - rename
    - ssh-copy-id
    - vim
    - watch
    - wget
    - zsh
    - zsh-completions
    - httpie
    - tree
    - openssl
    - coreutils
    - findutils
    - cask
    - htop
    - mvn
    - nvm
    - virtualenv
    - virtualenvwrapper
    - byobu
    - rvm

- name: Install apps with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - atom
    - iterm2
    - macpass
    - vlc
    - vagrant
    - vagrant-manager
    - font-hack
    - github-desktop
    - virtualbox

## Here install this: https://github.com/chriskempson/tomorrow-theme/tree/master/iTerm2

- name: Cleanup Brew packages
  command: brew cleanup
