#
# zPlug as package manager
#
source ~/.zplug/init.zsh
# Supports oh-my-zsh plugins and the like
zplug "plugins/git",   from:oh-my-zsh
# Load theme file
zplug 'gcaracuel/bureau.zsh-theme', as:theme
zplug "lib/*", from:oh-my-zsh   # Load oh-my-zsh and then just select plugins
zplug "plugins/osx", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "plugins/brew", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "plugins/dnf", from:oh-my-zsh, if:"[[ $OSTYPE == *linux* ]]"
zplug "plugins/systemd", from:oh-my-zsh, if:"[[ $OSTYPE == *linux* ]]"
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/key-bindings", from:oh-my-zsh
zplug "plugins/pip", from:oh-my-zsh
zplug "plugins/common-aliases", from:oh-my-zsh
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/z", from:oh-my-zsh
zplug "plugins/virtualenv", from:oh-my-zsh
zplug "plugins/virtualenvwrapper", from:oh-my-zsh
zplug "plugins/svn", from:oh-my-zsh
zplug "plugins/thefuck", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh
zplug "plugins/node", from:oh-my-zsh
zplug "plugins/mvn", from:oh-my-zsh
zplug "plugins/docker", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-completions"
zplug "bbenne10/goenv"

# Install plugins if there are plugins that have not been installed
zplug check || zplug install
zplug load

# TO UPDATE USE (from time to time): z plug status

DEFAULT_USER=$USER

export PATH="/sbin/:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:$HOME/.local/bin:$HOME/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='/usr/bin/vim'
 else
   export EDITOR='/usr/bin/gvim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh" # OSX

# VirtualEnv
export WORKON_HOME=~/Envs
mkdir -p $WORKON_HOME
case `uname` in
  Darwin)
    source /usr/local/bin/virtualenvwrapper.sh
    ;;
  Linux)
    source /usr/bin/virtualenvwrapper.sh
    ;;
esac

# RVM
rvm_silence_path_mismatch_check_flag=1     # This silence a dummy bug when using RVM and virtualenv at the same time
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

PERL_MB_OPT="--install_base \"/home/gcaracuel/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/gcaracuel/perl5"; export PERL_MM_OPT;

# GOENV
export GOPATH=~/.goenvs/gopath
export GO_ENV=~/.goenvs

# JAVA
# export JAVA_HOME=$(/usr/libexec/java_home)

# MVN
alias mvn="mvn-color"

# Aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

# BYOBU aliases
alias b='byobu'

# Vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
