---
- name: Add Virtualbox repo
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    gpgcheck: no
  become: yes
  become_method: sudo

- name: Add Spotify repo
  yum_repository:
    name: spotify
    description: Spotify Negativo17 $releasever - $basearch - VirtualBox
    baseurl: http://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    enabled: yes
    gpgkey: http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes
  become: yes
  become_method: sudo

- name: Add Chrome repo
  yum_repository:
    name: google-chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
  become: yes
  become_method: sudo

- name: Add Golang repo
  yum_repository:
    name: go-repo-io
    description: Go-repo.io
    baseurl: https://mirror.go-repo.io/centos/$releasever/$basearch/
    enabled: yes
    gpgcheck: yes
  become: yes
  become_method: sudo

- name: Add Tilix terminal repo
  yum_repository:
    name: heikoada-terminix
    description: Copr repo for terminix
    baseurl: https://copr-be.cloud.fedoraproject.org/results/heikoada/terminix/fedora-$releasever-$basearch/
    enabled: yes
    gpgcheck: yes
  become: yes
  become_method: sudo

- name: Install rpmfusion-free yum repo
  dnf:
    name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
  become: yes
  become_method: sudo

- name: Install libraries using DNF
  dnf: name={{ item }} state=latest disable_gpg_check=yes
  become: yes
  become_method: sudo
  with_items:
    - bash
    - curl
    - git
    - htop
    - nmap
    - nodejs
    - python
    - python-pip
    - python-pycurl
    - libselinux-python
    - python3
    - vim
    - tmux
    - wget
    - zsh
    - https://github.com/atom/atom/releases/download/v1.23.3/atom.x86_64.rpm
    - httpie
    - byobu
    - maven
    - VirtualBox-5.1
    - google-chrome
    - spotify-client
    - asciinema
    - golang
    - tilix
    - qt5
    - zeal

- name: Install Gnome-Terminal theme
  shell: /bin/bash -c "rm setup-theme.sh ; wget https://raw.githubusercontent.com/chriskempson/tomorrow-theme/master/Gnome-Terminal/setup-theme.sh && chmod +x setup-theme.sh && alias gconftool=gconftool-2 && ./setup-theme.sh"
  args:
    chdir: /tmp

- name: Install Insomnia REST
  get_url:
    url: https://builds.insomnia.rest/downloads/linux/latest
    dest: $HOME/.insomnia/Insomnia.Appimage
    force: yes
    mode: 0644

- include: oracle_java.yml
  tags:
    - java

- include: ../common/tasks/pip3.yml
  with_items:
    - asciinema
  tags: pip

- name: Install SDK
  shell: /bin/bash -c "curl -s "https://get.sdkman.io" | bash"
