---
- name: Add Virtualbox repo
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    gpgcheck: no
  become: yes
  become_method: sudo
- name: Add Spotify repo
  yum_repository:
    name: spotify
    description: Spotify Negativo17 $releasever - $basearch - VirtualBox
    baseurl: http://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    enabled: yes
    gpgkey: http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes
  become: yes
  become_method: sudo
- name: Add Chrome repo
  yum_repository:
    name: google-chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
  become: yes
  become_method: sudo

- name: Install rpmfusion-free yum repo
  dnf:
    name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
  become: yes
  become_method: sudo

- name: Install libraries using DNF
  dnf: name={{ item }} state=latest disable_gpg_check=yes
  become: yes
  become_method: sudo
  with_items:
    - bash
    - curl
    - git
    - htop
    - nmap
    - nodejs
    - python
    - python-pip
    - python-pycurl
    - libselinux-python
    - python3
    - vim
    - tmux
    - wget
    - zsh
    - https://github.com/atom/atom/releases/download/v1.11.2/atom.x86_64.rpm
    - httpie
    - byobu
    - maven
    - VirtualBox-5.1
    - google-chrome
    - spotify-client
    - asciinema

- name: Install Gnome-Terminal theme
  shell: /bin/bash -c "rm setup-theme.sh ; wget https://raw.githubusercontent.com/chriskempson/tomorrow-theme/master/Gnome-Terminal/setup-theme.sh && chmod +x setup-theme.sh && alias gconftool=gconftool-2 && ./setup-theme.sh"
  args:
    chdir: /tmp

- include: oracle_java.yml
  tags:
    - java

- include: ../common/tasks/pip3.yml
  with_items:
    - asciinema
  tags: pip
