---
- name: Add Virtualbox repo
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    gpgcheck: yes
  become: yes
  become_method: sudo

- name: Install libraries using DNF
  dnf: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
    - bash
    - curl
    - git
    - htop
    - nmap
    - nodejs
    - python
    - python-pip
    - python-pycurl
    - libselinux-python
    - python3
    - vim
    - tmux
    - wget
    - zsh
    - https://github.com/atom/atom/releases/download/v1.11.2/atom.x86_64.rpm
    - httpie
    - byobu
    - maven
    - VirtualBox-5.1

- name: Install Gnome-Terminal theme
  shell: /bin/bash -c "rm setup-theme.sh ; wget https://raw.githubusercontent.com/chriskempson/tomorrow-theme/master/Gnome-Terminal/setup-theme.sh && chmod +x setup-theme.sh && alias gconftool=gconftool-2 && ./setup-theme.sh"
  args:
    chdir: /tmp
