---
- name: Install Atom addons
  command: apm install {{ item }} chdir=~
  with_items:
    - merge-conflicts
  # IS NOT WORKING
    - atom-beautify
    - file-icons
    - linter
    - pigments
    - minimap
