---
- name: Install Atom addons
  command: apm install {{ item }} chdir=~
  with_items:
    - merge-conflicts
    - atom-beautify
    - file-icons
    - linter
    - pigments
    - minimap
    - sort-lines
    - fonts
    - Tomorrow-Night-Eighties
    - Monokai-slate
    - atom-material-ui
    - split-diff
    - go-plus
    - atom-jinja2
    - language-terraform
