---
- name: Backup old dotfiles
  file: src=~/.{{ item }}
        dest=~/.{{ item }}.ansible_date_time.epoch_backup
        state=file
        force=yes
- name: Symlink my dotfiles
  file: src=./dotfiles/{{ item }}
        dest=~/.{{ item }}
        state=link
        force=yes
