- file:
    path: ~/.dotfiles_backups/
    state: directory
    recurse: yes
  tags: dotfiles

- include: dotfiles.yml
  with_items:
    - vimrc
    - zshrc
    - gitignore_global
    - gitconfig
    - tmux.conf
    - npmrc
    - atom/config.cson
    - vim/colors/Tomorrow-Night-Eighties.vim
  tags: dotfiles

- name: Installing Antigen
  git: repo=https://github.com/zsh-users/antigen.git dest=~/.antigen clone=yes update=yes
  tags: dotfiles

- name: Downloading (custom) oh my zsh
  git: repo=https://github.com/gcaracuel/oh-my-zsh dest=~/.oh-my-zsh/ clone=yes update=yes
  tags: dotfiles

- name: Change shell to ZSH
  become: yes
  become_method: sudo
  user: shell=/bin/zsh name=root

- include: pip.yml
  with_items:
    - virtualenv
    - virtualenvwrapper
    - ipython

- include: nvm.yml
- include: atom.yml
- include: vim.yml
- include: fonts.yml
- include: rvm.yml
