- include: dotfiles.yml
  with_items:
    - vimrc
    - zshrc
    - gitignore_global
    - gitconfig
    - tmux.conf
    - npmrc
    - atom/

- name: Dowloading (custom) oh my zsh
  git:  repo=https://github.com/gcaracuel/oh-my-zsh dest==~/.oh-my-zsh/ clone=yesc update=yes

- name: Change shell to ZSH
  become: yes
  become_method: sudo
  user: shell=/bin/zsh name=root

- name: Install Powerline fonts
  pip: name='git+https://github.com/powerline/powerline/tree/develop'

- name: Install Atom addons
  command: apm install {{ item }}
  with_items:
    - merge-conflicts
    - atom-beautify
    - file-icons
