- file:
    path: ~/.dotfiles_backups/
    state: directory
    recurse: yes
  tags: dotfiles

- include: dotfiles.yml
  with_items:
    - vimrc
    - zshrc
    - gitignore_global
    - gitconfig
    - tmux.conf
    - npmrc
    - atom/config.cson
    - vim/colors/Tomorrow-Night-Eighties.vim
  tags: dotfiles

- name: Installing zPlug
  git: repo=https://github.com/zplug/zplug dest=~/.zplug clone=yes update=yes
  tags: dotfiles

- name: Change shell to ZSH
  user: shell=/bin/zsh user={{ item }}
  become: true
  become_method: sudo
  with_items:
    - root
    - gcaracuel
  tags: dotfiles

- include: pip.yml
  with_items:
    - virtualenv
    - virtualenvwrapper
    - ipython
    - thefuck
  tags: pip

- include: nvm.yml
- include: atom.yml
- include: vim.yml
- include: fonts.yml
- include: rvm.yml
