- file:
    path: ~/.dotfiles_backups/
    state: directory
    recurse: yes
  tags: dotfiles

- include: dotfiles.yml
  with_items:
    - vimrc
    - zshrc
    - gitignore_global
    - gitconfig
    - tmux.conf
    - npmrc
    - atom/config.cson
    - vim/colors/Tomorrow-Night-Eighties.vim
  tags: dotfiles

- name: Dowloading (custom) oh my zsh
  git: repo=https://github.com/gcaracuel/oh-my-zsh dest=~/.oh-my-zsh/ clone=yes update=yes
  tags: dotfiles

- name: Change shell to ZSH
  become: yes
  become_method: sudo
  user: shell=/bin/zsh name=root

- name: Install Atom addons
  command: apm install {{ item }} chdir=~
  with_items:
    - merge-conflicts
  # IS NOT WORKING
  #  - atom-beautify
    - file-icons
    - linter
    - pigments
    - minimap

- name: Install Vundle VIM package manager
  git:  repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim clone=yes update=yes
- name: Install VIM plugins
  command: vim +PluginInstall +qall
- name: Ensure VIM tmp dir exists
  file: path=~/.vim/tmp state=directory mode=0700

- name: Cloning Powerline Fonts
  git: repo=https://github.com/powerline/fonts.git dest=/tmp/fonts/ clone=yes update=yes
- name: Install Powerline Fonts (script)
  command: /tmp/fonts/install.sh
- name: Install Powerline fonts (pip)
  pip: name=powerline-status
  become: yes
  become_method: sudo
