- file:
    path: ~/.dotfiles_backups/
    state: directory
    recurse: yes
  tags: dotfiles

- include: dotfiles.yml
  with_items:
    - vimrc
    - zshrc
    - gitignore_global
    - gitconfig
    - tmux.conf
    - npmrc
    - atom/config.cson
    - vim/colors/Tomorrow-Night-Eighties.vim
  tags: dotfiles

# OSX only
- name: Copy iTerm2 configuration 
  ansible.builtin.file: 
    src: ~/dotfiles/dotfiles/osx/com.googlecode.iterm2.plist
    dest: ~/Library/Preferences/com.googlecode.iterm2.plist
    state: link
    force: yes
    follow: yes
  when: "ansible_os_family == 'Darwin'"

- name: Copy Spectacle configuration 
  ansible.builtin.file: 
    src: ~/dotfiles/dotfiles/osx/Spectacle_Shortcuts.json
    dest: "~/Library/Application Support/Spectacle/Shortcuts.json"
    state: link
    force: yes
    follow: yes
  when: "ansible_os_family == 'Darwin'"

# TO-DO iTerm2 Theme - https://github.com/chriskempson/tomorrow-theme/tree/master/iTerm2

- name: Change shell to ZSH
  user: shell=/bin/zsh user={{ item }}
  become: true
  become_method: sudo
  with_items:
    - root
    - gcaracuel
  tags: dotfiles

- include: pip3.yml
  with_items:
    - virtualenv
    - virtualenvwrapper
    - ipython
    - thefuck
  tags: pip

- include: nvm.yml
- include: vscode.yml
- include: vim.yml
- include: fonts.yml
- include: rvm.yml
- include: golang.yml
