- file:
    path: ~/.dotfiles_backups/
    state: directory
    recurse: yes
  tags: dotfiles

- include: dotfiles.yml
  with_items:
    - vimrc
    - zshrc
    - gitignore_global
    - gitconfig
    - tmux.conf
    - npmrc
    - starship.toml
    - vim/colors/Tomorrow-Night-Eighties.vim
  tags: dotfiles

- name: Link VSCode configuration 
  ansible.builtin.file: 
    src: "{{ playbook_dir }}/../dotfiles/vscode_settings.json"
    dest: "~/Library/Application Support/Code/User/settings.json"
    state: link
    force: yes
    follow: yes
  tags: dotfiles

- name: Link Github Dash config
  ansible.builtin.file: 
    src: "{{ playbook_dir }}/../dotfiles/gh_dash.yml"
    dest: "~/.config/gh-dash/config.yml"
    state: link
    force: yes
    follow: yes
  tags: onlyme

# OSX only
- name: Copy iTerm2 configuration 
  ansible.builtin.file: 
    src: "{{ playbook_dir }}/../dotfiles/osx/iterm2.json"
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/gcaracuel.json"
    state: link
    force: yes
    follow: yes
  when: "ansible_os_family == 'Darwin'"
  tags: dotfiles

- name: Copy Spectacle configuration 
  ansible.builtin.file: 
    src: ~/dotfiles/dotfiles/osx/Spectacle_Shortcuts.json
    dest: "~/Library/Application Support/Spectacle/Shortcuts.json"
    state: link
    force: yes
    follow: yes
  when: "ansible_os_family == 'Darwin'"
  tags: dotfiles

- name: Change shell to ZSH
  user: shell=/bin/zsh user={{ item }}
  become: true
  become_method: sudo
  with_items:
    - root
    - gcaracuel
  tags: dotfiles

- include: pip3.yml
  with_items:
    - virtualenv
    - virtualenvwrapper
    - ipython
    - thefuck
  tags: pip

- include: nvm.yml
- include: vscode.yml
- include: vim.yml
- include: fonts.yml
- include: rvm.yml
- include: golang.yml
