#!/bin/bash

# by default, tile all windows
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

# Yabai rules - It wont work fine until System Integrity Protection: Filesystem Protections and Debugging Restrictions are disabled
yabai -m rule --add app="^System Settings$" layer=above manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Ghostty$" space=1
yabai -m rule --add app="^Code$" space=2

yabai -m window --focus recent

yabai -m config external_bar all:32:0